services:
  unit:
    build:
      context: ./uni-verse-api/
      dockerfile: Dockerfile.test
    volumes:
      - ./uni-verse-api:/usr/src/app
      - ./api-logs:/usr/src/app/logs
    restart: never
    env_file:
      - docker.env

  e2e:
    build:
      context: ./uni-verse-api/
      dockerfile: Dockerfile.test
    command: npm run test:e2e
    volumes:
      - ./uni-verse-api:/usr/src/app
      - ./api-logs:/usr/src/app/logs
    restart: never
    env_file:
      - docker.env
  #  frontend:
  #  build:
  #  context: .
  #  dockerfile: ./uni-verse-frontend/Dockerfile.dev
  #command: npm run dev
  #ports:
  #  - 3005:3005
  #depends_on:
  #  - mongodb
  # - minio
  # - rabbitmq
  # - api
  #volumes:
  #  - ./uni-verse-frontend:/usr/src/app
  # - /usr/src/app/node_modules
  # - ./froentend-logs:/usr/src/app/logs
  #restart: unless-stopped
  #env_file:
  #  - docker.env
